### ISSUE TITLE
Release compatible with Dune 3

### ISSUE THREAD

**Issue by CraigFe** [c-cube/printbox#23]
Thanks for this excellent library!

Could we get a release with the Dune 3 compat fix (https://github.com/c-cube/printbox/pull/22) shortly?

We're currently using this library in Irmin, and would appreciate being able to upgrade to Dune 3 as soon as possible :-)

**Comment by c-cube** [comment]
https://github.com/ocaml/opam-repository/pull/20782 hopefully :crossed_fingers:
