### ISSUE TITLE
Better Unicode advice

### ISSUE THREAD

**Issue by dbuenzli** [c-cube/printbox#4]
The advice [here](https://github.com/c-cube/printbox/blob/ab954cf1f579677dcb7345b89dcd4ee392068b67/src/PrintBox_text.mli#L10-L18) is very inaccurate, unless you only care about US-ASCII, counting scalar values will not give you good a visual length, please do not dispel such an idea.

Better advice would be to either count the grapheme clusters (e.g. using [Uuseg_string](https://erratique.ch/software/uuseg/doc/Uuseg_string.html)) and/or accumulate on the scalar values @pqwy's carefully crafted [`Uucp.Break.tty_width_hint`](https://erratique.ch/software/uucp/doc/Uucp.Break.html#VALtty_width_hint) whose doc string also gives a nice overview of the challenges for terminal width measurements.

**Comment by c-cube** [comment]
I'm trying to improve that, and stumbled upon the following:

```ocaml
let str = "aéo\nπ/2\nτ/4";;
Uutf.String.fold_utf_8 ~pos:5 ~len:4 (fun _ _ _ -> ()) () str;;
```

raises

```
Exception: Invalid_argument "String.sub / Bytes.sub".
Raised at file "pervasives.ml", line 33, characters 25-45
Called from file "src/uutf.ml", line 54, characters 33-57
Called from file "src/uutf.ml", line 730, characters 33-52
```

even though `String.sub str 5 4` works fine. Am I using it wrong?

**Comment by dbuenzli** [comment]
Humpf, looking at `uutf`'s repo the [latest commit](https://github.com/dbuenzli/uutf/commit/f9e3395f04e646b481a35e11e19af66cf9c62f06) seems to be a fix about that which was made a year ago... It seems it never got into a release.

If you can confirm me your problems are gone with:
```
opam pin uutf --dev
```
I'll gladly push out a release.

**Comment by c-cube** [comment]
Yes, it does now work on branch `fix-4`, with a [new test](https://github.com/c-cube/printbox/tree/45013e5d4689909adcdd6dd3bb73d7bac8ece603#handling-unicode). I used uutf+uucp.
